'use client';
import { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { clientAuth, clientDb } from '@/lib/firebase';
import { createUserWithEmailAndPassword, onAuthStateChanged, signInWithEmailAndPassword, signOut, User } from 'firebase/auth';
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, onSnapshot, query, serverTimestamp, setDoc, updateDoc, where } from 'firebase/firestore';

type Settings = { prework:boolean; prd:boolean; share:boolean };
const initialSettings: Settings = { prework:true, prd:false, share:false };
const emptyPrd = { problem:'', user:'', goal:'', features:'' };
export default function Home() {
 const [user,setUser]=useState<User|null>(null), [profile,setProfile]=useState<any>(null), [settings,setSettings]=useState<Settings>(initialSettings), [view,setView]=useState('prework');
 const [login,setLogin]=useState({email:'',password:''}), [signup,setSignup]=useState({nickname:'',email:'',password:''}), [message,setMessage]=useState('');
 const [prework,setPrework]=useState(''), [prd,setPrd]=useState(emptyPrd), [project,setProject]=useState<any>({name:'',url:'',problem:'',features:'',guide:'',isPublic:false}), [projects,setProjects]=useState<any[]>([]), [allProjects,setAllProjects]=useState<any[]>([]), [content,setContent]=useState(''); const [users,setUsers]=useState<any[]>([]);
 useEffect(()=>onAuthStateChanged(clientAuth(), async u=>{setUser(u); if(!u) return; const p=await getDoc(doc(clientDb(),'users',u.uid)); setProfile(p.data());}),[]);
 useEffect(()=>onSnapshot(doc(clientDb(),'settings','site'),s=>setSettings(s.exists()?s.data() as Settings:initialSettings),()=>setSettings(initialSettings)),[]);
 useEffect(()=>{fetch('/content/problem-statement-assignment.md').then(r=>r.text()).then(setContent)},[]);
 useEffect(()=>{ if(!user) return; const db=clientDb(); getDoc(doc(db,'prework',user.uid)).then(x=>setPrework(x.data()?.text||'')); getDoc(doc(db,'prds',user.uid)).then(x=>setPrd({...emptyPrd,...(x.data()||{})})); getDocs(query(collection(db,'projects'),where('ownerId','==',user.uid))).then(x=>{const first=x.docs[0];if(first)setProject({...first.data(),id:first.id})}); },[user]);
 useEffect(()=>{if(!user)return; const q=query(collection(clientDb(),'projects'),where('isPublic','==',true)); return onSnapshot(q,s=>setProjects(s.docs.map(d=>({id:d.id,...d.data()}))));},[user]);
 const isAdmin=!!profile && profile.role==='admin'; const allowed=(key:keyof Settings)=>isAdmin||settings[key];
 async function register(e:React.FormEvent){e.preventDefault();setMessage(''); const r=await fetch('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(signup)});const d=await r.json(); if(!r.ok)return setMessage(d.error); await signInWithEmailAndPassword(clientAuth(),signup.email,signup.password); setMessage('Account created. Keep your password private.');}
 async function signIn(e:React.FormEvent){e.preventDefault(); try{await signInWithEmailAndPassword(clientAuth(),login.email,login.password)}catch{setMessage('We could not sign you in. Please check your details and try again.')}}
 async function savePrework(){if(!user)return;await setDoc(doc(clientDb(),'prework',user.uid),{text:prework,updatedAt:serverTimestamp()});setMessage('Pre-work saved.');}
 async function savePrd(){if(!user)return;await setDoc(doc(clientDb(),'prds',user.uid),{...prd,updatedAt:serverTimestamp()});setMessage('PRD saved.');}
 function downloadPrd(){const t=`# ${profile?.nickname || 'SchoolLab'} PRD\n\n## Problem\n${prd.problem}\n\n## User\n${prd.user}\n\n## Goal\n${prd.goal}\n\n## Core features\n${prd.features}\n`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:'text/markdown'}));a.download='schoollab-prd.md';a.click();}
 async function saveProject(){if(!user)return;try{new URL(project.url)}catch{return setMessage('Please enter a valid MVP URL.')} const data={...project,ownerId:project.ownerId||user.uid,ownerName:project.ownerName||profile?.nickname||user.displayName,updatedAt:serverTimestamp()};if(project.id)await updateDoc(doc(clientDb(),'projects',project.id),data);else{const ref=doc(collection(clientDb(),'projects'));await setDoc(ref,data);setProject({...project,id:ref.id})}setMessage('MVP submission saved.');}
 async function removeProject(id:string){if(!confirm('Delete this MVP submission? This cannot be undone.'))return;await deleteDoc(doc(clientDb(),'projects',id));if(project.id===id)setProject({name:'',url:'',problem:'',features:'',guide:'',isPublic:false});setMessage('MVP submission deleted.');}
 async function toggle(key:keyof Settings){await setDoc(doc(clientDb(),'settings','site'),{[key]:!settings[key]},{merge:true});}
 async function loadUsers(){const token=await user?.getIdToken();const r=await fetch('/api/admin/users',{headers:{Authorization:`Bearer ${token}`}});setUsers(await r.json());const p=await getDocs(collection(clientDb(),'projects'));setAllProjects(p.docs.map(x=>({id:x.id,...x.data()})));}
 async function editUser(uid:string,nickname:string,password:string){const token=await user?.getIdToken();const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({uid,nickname,password})});const d=await r.json();setMessage(d.ok?'User account updated.':d.error);loadUsers();}
 if(!user) return <main className="shell"><section className="hero"><h1>APEX SchoolLab</h1><p>Turn a school challenge into a thoughtful MVP.</p></section><div className="grid"><form className="card" onSubmit={signIn}><h2>Sign in</h2><label>Email</label><input type="email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/><label>Password</label><input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><p><button>Sign in</button></p></form><form className="card" onSubmit={register}><h2>Create an account</h2><label>Nickname</label><input required value={signup.nickname} onChange={e=>setSignup({...signup,nickname:e.target.value})}/><label>Email</label><input required type="email" value={signup.email} onChange={e=>setSignup({...signup,email:e.target.value})}/><label>Password</label><input required minLength={8} type="password" value={signup.password} onChange={e=>setSignup({...signup,password:e.target.value})}/><p className="muted">We use your email only for account recovery and workshop communication. Do not enter student names or sensitive school information.</p><button>Create account</button></form></div>{message&&<p className="error">{message}</p>}</main>;
 return <main className="shell"><section className="hero"><div className="row spread"><div><h1>APEX SchoolLab</h1><p>Welcome, {profile?.nickname || user.displayName}.</p></div><button className="secondary" onClick={()=>signOut(clientAuth())}>Sign out</button></div><div className="steps"><span className={'step '+(prework?'done':'')}>1. Pre-work</span><span className={'step '+(prd.problem?'done':'')}>2. PRD</span><span className={'step '+(project.id?'done':'')}>3. Share your MVP</span></div></section><nav className="nav">{(['prework','prd','share','gallery'] as const).filter(x=>x==='gallery'||allowed(x as keyof Settings)).map(x=><button className={view===x?'active':'secondary'} onClick={()=>setView(x)} key={x}>{x==='share'?'Share your MVP':x==='prd'?'Write PRD':x[0].toUpperCase()+x.slice(1)}</button>)}{isAdmin&&<button className={view==='admin'?'active':'secondary'} onClick={()=>{setView('admin');loadUsers()}}>Admin</button>}</nav>{message&&<p className="notice">{message}</p>}
 {view==='prework'&&<section className="card"><div className="markdown"><ReactMarkdown>{content}</ReactMarkdown></div><label>Your problem statement</label><textarea placeholder="[WHO] struggle(s) to ..." value={prework} onChange={e=>setPrework(e.target.value)}/><p><button onClick={savePrework}>Save pre-work</button></p></section>}
 {view==='prd'&&allowed('prd')&&<section className="card"><h2>Write your PRD</h2><p className="muted">Your saved problem statement: {prework || 'No pre-work saved yet.'}</p>{([['problem','What problem are you trying to address?'],['user','Who will use the app?'],['goal','What should users be able to do with the app?'],['features','What are the one or two most important features?']] as const).map(([key,label])=><div key={key}><label>{key==='features'?'Core features':key[0].toUpperCase()+key.slice(1)}</label><textarea placeholder={label} value={prd[key]} onChange={e=>setPrd({...prd,[key]:e.target.value})}/></div>)}<p className="row"><button onClick={savePrd}>Save PRD</button><button className="secondary" onClick={downloadPrd}>Download Markdown</button></p></section>}
 {view==='share'&&allowed('share')&&<section className="card"><h2>Share your MVP</h2>{([['name','App or project name'],['url','MVP link'],['problem','Problem addressed'],['features','Core features'],['guide','Optional introduction or instructions']] as const).map(([key,label])=><div key={key}><label>{label}</label>{key==='url'||key==='name'?<input value={project[key]||''} onChange={e=>setProject({...project,[key]:e.target.value})}/>:<textarea value={project[key]||''} onChange={e=>setProject({...project,[key]:e.target.value})}/>}</div>)}<label><input style={{width:'auto'}} type="checkbox" checked={project.isPublic} onChange={e=>setProject({...project,isPublic:e.target.checked})}/> Show this MVP to other participants</label><p className="row"><button onClick={saveProject}>Save submission</button>{project.id&&<button className="danger" onClick={()=>removeProject(project.id)}>Delete submission</button>}{project.url&&<a href={project.url} target="_blank">Preview external link ↗</a>}</p></section>}
 {view==='gallery'&&<section className="card"><h2>Shared MVPs</h2>{projects.length?projects.map(p=><ProjectCard project={p} user={user} isAdmin={isAdmin} key={p.id}/>):<p className="muted">No public MVPs yet.</p>}</section>}
 {view==='admin'&&isAdmin&&<section className="card"><h2>Administrator controls</h2><p>Administrators always see every workflow screen, even when it is hidden for participants.</p><div className="grid">{(['prework','prd','share'] as const).map(key=><div className="card" key={key}><strong>{key==='share'?'Share your MVP':key==='prd'?'PRD':'Pre-work'}</strong><p>{settings[key]?'Visible to participants':'Hidden from participants'}</p><button className="secondary" onClick={()=>toggle(key)}>{settings[key]?'Hide menu':'Open menu'}</button></div>)}</div><h3>Participant accounts</h3><table className="admin-table"><thead><tr><th>Nickname</th><th>Email</th><th>New password</th><th></th></tr></thead><tbody>{Array.isArray(users)&&users.map(u=><UserRow key={u.uid} user={u} onSave={editUser}/>)}</tbody></table><h3>All MVP submissions</h3>{allProjects.map(p=><article className="project" key={p.id}><strong>{p.name}</strong><span className="muted"> · {p.ownerName} · {p.isPublic?'Public':'Private'}</span><p className="row"><button className="secondary" onClick={()=>{setProject(p);setView('share')}}>Edit submission</button><button className="danger" onClick={()=>removeProject(p.id)}>Delete submission</button></p></article>)}</section>}</main>;
}
function UserRow({user,onSave}:{user:any,onSave:(id:string,n:string,p:string)=>void}){const[n,setN]=useState(user.nickname||''),[p,setP]=useState('');return <tr><td><input value={n} onChange={e=>setN(e.target.value)}/></td><td>{user.email}</td><td><input type="password" placeholder="Leave blank to keep" value={p} onChange={e=>setP(e.target.value)}/></td><td><button onClick={()=>onSave(user.uid,n,p)}>Update</button></td></tr>}
function ProjectCard({project,user,isAdmin}:{project:any,user:User,isAdmin:boolean}){const[comments,setComments]=useState<any[]>([]),[text,setText]=useState('');useEffect(()=>onSnapshot(collection(clientDb(),'projects',project.id,'comments'),s=>setComments(s.docs.map(d=>({id:d.id,...d.data()})))),[project.id]);async function post(){if(!text.trim())return;await addDoc(collection(clientDb(),'projects',project.id,'comments'),{text:text.trim(),authorId:user.uid,authorName:user.displayName||'Participant',createdAt:serverTimestamp()});setText('')}async function edit(c:any){const text=prompt('Edit your feedback',c.text);if(text?.trim())await updateDoc(doc(clientDb(),'projects',project.id,'comments',c.id),{text:text.trim(),updatedAt:serverTimestamp()})}return <article className="project"><h3>{project.name}</h3><p>{project.problem}</p><p className="muted">By {project.ownerName}</p><p><a href={project.url} target="_blank">Open external MVP ↗</a></p><div className="card"><strong>Feedback</strong>{comments.map(c=><div className="project" key={c.id}><span>{c.text}</span><p className="muted">{c.authorName} {c.createdAt?.toDate?.().toLocaleString?.()||'just now'} {(c.authorId===user.uid||isAdmin)&&<><button className="secondary" onClick={()=>edit(c)}>Edit</button> <button className="danger" onClick={()=>deleteDoc(doc(clientDb(),'projects',project.id,'comments',c.id))}>Delete</button></>}</p></div>)}<div className="row"><input aria-label="Feedback" placeholder="Leave constructive feedback" value={text} onChange={e=>setText(e.target.value)}/><button onClick={post}>Post</button></div></div></article>}
